-- 1. Weather Observations
-- Station (id, city, state, lat_n, long_w)

SELECT CITY, STATE FROM Station;

SELECT CITY 
FROM Station
WHERE ID % 2 = 0;

SELECT COUNT(CITY) - COUNT(DISTINCT CITY) AS Duplicate_Cities
FROM Station;

SELECT DISTINCT CITY FROM Station
WHERE CITY LIKE 'A%' 
   OR CITY LIKE 'E%' 
   OR CITY LIKE 'I%' 
   OR CITY LIKE 'O%' 
   OR CITY LIKE 'U%';

SELECT DISTINCT CITY FROM Station
WHERE CITY LIKE '%A' 
   OR CITY LIKE '%E' 
   OR CITY LIKE '%I' 
   OR CITY LIKE '%O' 
   OR CITY LIKE '%U';

SELECT DISTINCT CITY FROM Station
WHERE CITY LIKE 'A%A' 
   OR CITY LIKE 'E%E' 
   OR CITY LIKE 'I%I' 
   OR CITY LIKE 'O%O' 
   OR CITY LIKE 'U%U';

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE '%A'
  AND CITY NOT LIKE '%E'
  AND CITY NOT LIKE '%I'
  AND CITY NOT LIKE '%O'
  AND CITY NOT LIKE '%U';

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%'
  AND CITY NOT LIKE 'E%'
  AND CITY NOT LIKE 'I%'
  AND CITY NOT LIKE 'O%'
  AND CITY NOT LIKE 'U%';

SELECT DISTINCT CITY FROM Station
WHERE CITY LIKE 'A%A' 
  AND CITY LIKE 'E%E' 
  AND CITY LIKE 'I%I' 
  AND CITY LIKE 'O%O' 
  AND CITY LIKE 'U%U';

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%'
  AND CITY NOT LIKE 'E%'
  AND CITY NOT LIKE 'I%'
  AND CITY NOT LIKE 'O%'
  AND CITY NOT LIKE 'U%'
OR    CITY NOT LIKE '%A'
  AND CITY NOT LIKE '%E'
  AND CITY NOT LIKE '%I'
  AND CITY NOT LIKE '%O'
  AND CITY NOT LIKE '%U';;